-- Jesus
INSERT INTO aviones (matricula, marca, modelo) VALUES ("EC", "Boeing", "Boeing 737-100")
INSERT INTO aviones (matricula) VALUES ("EC", "Boeing", "Boeing 737-100");
INSERT INTO aviones (matricula) VALUES ("YA", "Airbus", "Airbus A320");
INSERT INTO aviones (matricula) VALUES ("ZA", "Embraer", "E-Jet");
INSERT INTO aviones (matricula) VALUES ("D", "Airbus", "Airbus A380");
INSERT INTO aviones (matricula) VALUES("7T", "Airbus", "Airbus A318");
INSERT INTO aviones (matricula) VALUES ("C3", "Airbus", "Airbus A319");
INSERT INTO aviones (matricula) VALUES ("D2", "Airbus", "Airbus A320");
INSERT INTO viones (matricula) VALUES ("VP-A", "Airbus", "Airbus A321");
INSERT INTO aviones (matricula) VALUES ("V2", "Airbus", "Airbus A330-200");
INSERT INTO aviones (matricula) VALUES ("F-OG", "Airbus", "Airbus A330-300");
INSERT INTO aviones (matricula) VALUES ("PJ", "Airbus", "Airbus A350-900"); 
INSERT INTO aviones (matricula) VALUES ("HZ", "Airbus", "Airbus A350-1000"); 
INSERT INTO aviones (matricula) VALUES ("LQ", "Airbus", "Airbus A380");
INSERT INTO aviones (matricula) VALUES ("EK", "Airbus", "Airbus A300");
INSERT INTO aviones (matricula) VALUES ("P4", "Airbus", "Airbus A310");
INSERT INTO aviones (matricula) VALUES ("VH", "Boeing", "Boeing 737-200");
INSERT INTO aviones (matricula) VALUES ("OE", "Boeing", "Boeing 737-300"); 
INSERT INTO aviones (matricula) VALUES ("4K", "Boeing", "Boeing 737-400"); 
INSERT INTO aviones (matricula) VALUES ("C6", "Boeing", "Boeing 737-500");
INSERT INTO aviones (matricula) VALUES ("A9C", "Boeing", "Boeing 737-600");
INSERT INTO aviones (matricula) VALUES ("S2", "Boeing", "Boeing 737-700");
INSERT INTO aviones (matricula) VALUES ("8P", "Boeing", "Boeing 737-800"); 
INSERT INTO aviones (matricula) VALUES ("OO", "Boeing", "Boeing 737-900");
INSERT INTO aviones (matricula) VALUES ("V3", "Boeing", "Boeing 737 MAX 7"); 
INSERT INTO aviones (matricula) VALUES ("TY", "Boeing", "Boeing 737 MAX 8");
INSERT INTO aviones (matricula) VALUES ("VP-B", "Boeing", "Boeing 737 MAX 9");
INSERT INTO aviones (matricula) VALUES ("A5", "Boeing", "Boeing 737 MAX 10");
INSERT INTO aviones (matricula) VALUES ("EW", "Boeing", "Boeing 737-100");
INSERT INTO aviones (matricula) VALUES ("CP", "Embraer", "ERJ 135");
INSERT INTO aviones (matricula) VALUES ("T9", "Embraer", "Embraer EMB 110 Bandeirante");
INSERT INTO aviones (matricula) VALUES ("A2", "Embraer", "Embraer EMB 120 Brasilia");
INSERT INTO aviones (matricula) VALUES ("PP", "Embraer", "Embraer E-Jet E170");
INSERT INTO aviones (matricula) VALUES ("V8", "Embraer", "Embraer E-Jet E175"); 
INSERT INTO aviones (matricula) VALUES ("LZ", "Embraer", "Embraer E-Jet E190");
INSERT INTO aviones (matricula) VALUES ("XT", "Embraer", "Embraer E-Jet E195"); 
INSERT INTO aviones (matricula) VALUES ("9U", "Embraer", "Embraer EMB 145");
INSERT INTO aviones (matricula) VALUES ("XU", "Embraer", "Embraer Praetor 500");
INSERT INTO aviones (matricula) VALUES ("TJ", "Embraer", "Embraer Praetor 600");
INSERT INTO aviones (matricula) VALUES ("C", "Boeing", "Boeing 747-200");
INSERT INTO aviones (matricula) VALUES ("D4", "Boeing", "Boeing 747-300"); 
INSERT INTO aviones (matricula) VALUES ("TT", "Boeing", "Boeing 747-400");
INSERT INTO aviones (matricula) VALUES ("CC", "Boeing", "Boeing 747-8"); 
INSERT INTO vuelos (id_vuelo, fecha_hora_vuelo, duracion) VALUES ("","","")